config/routes.rb
Moika::Application.routes.draw do


  get 'mobile/admin'
  get 'mobile/requests'
  get 'mobile/subscribes'
  # Sorry
  get 'about', to: 'static_pages#show', permalink: 'new_about' 

  resources :images, only:[:update, :destroy]


  resources :survey_results, only: [:index,:create]
  namespace :admin do
    resources :surveys
  end

  get 'proposals', to: 'proposals#index'
  resources :reviews, only: [:index]

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forum'


  resources 'news', only: [:index, :show], controller: 'posts', type: 'NewsPost', as: 'news_posts'
  resources 'info', only: [:index, :show], controller: 'posts', type: 'InfoPost', as: 'info_posts'
  get 'video', to: 'video_posts#index'
  # get 'temp_session/login'
  resources :temp_session
  # resources :navs

  get 'posts(/:id)', to: redirect('/news/%{id}')
  # resources :posts, only: [:index,:show]
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get "normal_users/show"
  root 'map#show'
  # get "map/show"

  get "sp/:id", to: "static_pages#show", as: "static_page"
  get "banners/update"

  get "user/:id", to: "users#show", as: '/user'
  get "users/registration", to: "users#registration", as: 'registration'
  get "users/login", to: "users#login", as: 'login'

  get "normal_user/:id", to: "normal_users#show", as: '/normal_user'

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :normal_users, controllers: { registrations: "registrations", sessions: "sessions" }

  get "update_password", to: "users#update_password", as: "/update_password"
  post "update_password", to: "users#update_password"
  # resource :user do
  #   collection do
  #     post 'update_password'
  #   end
  # end

  resources :car_washes do
    get :update_map, on: :collection
    patch :update_widget_of, on: :member
    resource :widget
    resources :comments, only: [:index, :create]
    resources :requests do 
      # some spammers got me always going to this page
      collection do
        get 'legal', to: 'requests#legal'
      end
    end
    resources :messages, only: [:index, :show, :update]
    resources :normal_user_messages
    resources :banners, only: [:index, :update]
    resources :payments, only: [:index]
    resources :invoices, only: [:new, :create, :show]
    delete 'delete_file/:id', to: 'banners#delete_file', as: '/delete_file'
    resources :reviews
    resources :videos, except: [:index]
    resources :images, except: [:index]
  end
  get 'car_washes/:id/edit(/:cw_tabs_selected_tab)', :to => 'car_washes#edit', as: 'edit_car_wash_with_tab'
  # get 'car_washes/:id(/:cw_tabs_selected_tab)', :to => 'car_washes#show', as: 'show_car_wash_with_tab'
  put 'car_washes/:id/update_main_action', to: 'car_washes#update_main_action', as: '/car_washes_update_main_action'
  post 'car_washes/:id/subscribe/:user_id', to: 'car_washes#subscribe', as: '/car_washes_subscribe'


  scope '/robokassa' do
    %w(paid success fail).map do |route|
      method(Rubykassa.http_method).call "/#{route}" => "robokassa##{route}", as: "robokassa_#{route}" 
    end
  end
  # controller :robokassa do
  #   get "robokassa/:notification_key/notify"   => :notify,  :as => :robokassa_notification
  #   get "robokassa/paid"   => :paid,  :as => :robokassa_payment

  #   get "robokassa/success"  => :success, :as => :robokassa_on_success
  #   get "robokassa/fail"     => :fail,    :as => :robokassa_on_fail
  # end

  namespace :admin do
    get '', to: 'dashboard#main', as: '/'
    # get 'ads', to: 'settings#ads_index', as: 'ad_settings'
    # put 'ads', to: 'settings#ads_update'
    patch 'cube_ads', to: 'advertisements#update', :type => 'CubeAd'
    patch 'marquee_ads', to: 'advertisements#update', :type => 'MarqueeAd'
    resources :cube_ads, :controller => 'advertisements', :type => 'CubeAd'
    resources :marquee_ads, :controller => 'advertisements', :type => 'MarqueeAd'
    resources :ad_settings
    resources :mq_settings
    resources :settings
    get 'load_data_from_ya', to: 'dashboard#load_data_from_ya', as: '/load_data_from_ya'
    post 'users/create_admin'
    get 'users/new_admin'
    post 'users/destroy_admin'
    resources :users
    resources :messages, only: [:index, :show, :create, :destroy]
    resources :banners
    resources :banners_config, only: [:update]
    resources :static_pages
    resources :car_washes
    resources :posts
    resources :news_posts, :controller => 'posts', :type => 'NewsPost'
    resources :info_posts, :controller => 'posts', :type => 'InfoPost'
    resources :video_posts
    resources :post_categories
    resources :navs do
      post :update_position, on: :collection
    end 
    # devise_for :users, only: [:update, :index, :show]
    get 'add_car_wash/:id', to: 'users#add_car_wash', as: '/add_car_wash'
    delete 'delete_file/:id', to: 'banners#delete_file', as: '/delete_file'
  end

  get ':permalink', to: 'static_pages#show'
  match "*path" => redirect("/"), via: :all


end

app/models/admin/survey.rb
class Admin::Survey < ActiveRecord::Base
  has_many :survey_results

  # def done
  # end
end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < AdminController
  before_action :set_admin_survey, only: [:show, :edit, :update, :destroy]

  # GET /admin/surveys
  # GET /admin/surveys.json
  def index
    @admin_surveys = Admin::Survey.all
  end

  # GET /admin/surveys/1
  # GET /admin/surveys/1.json
  def show
  end

  # GET /admin/surveys/new
  def new
    @admin_survey = Admin::Survey.new
  end

  # GET /admin/surveys/1/edit
  def edit
  end

  # POST /admin/surveys
  # POST /admin/surveys.json
  def create
    @admin_survey = Admin::Survey.new(admin_survey_params)

    respond_to do |format|
      if @admin_survey.save
        format.html { redirect_to @admin_survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @admin_survey }
      else
        format.html { render :new }
        format.json { render json: @admin_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/surveys/1
  # PATCH/PUT /admin/surveys/1.json
  def update
    respond_to do |format|
      if @admin_survey.update(admin_survey_params)
        format.html { redirect_to @admin_survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_survey }
      else
        format.html { render :edit }
        format.json { render json: @admin_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/surveys/1
  # DELETE /admin/surveys/1.json
  def destroy
    @admin_survey.destroy
    respond_to do |format|
      format.html { redirect_to admin_surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_survey
      @admin_survey = Admin::Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_survey_params
      params.require(:admin_survey).permit(:question, :answer_1, :answer_2, :answer_3, :answer_4, :answer_5)
    end
end

app/helpers/admin/surveys_helper.rb
module Admin::SurveysHelper
end

app/views/admin/surveys/_form.html.haml
= form_for @admin_survey do |f|
  - if @admin_survey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_survey.errors.count, "error")} prohibited this admin_survey from being saved:"
      %ul
        - @admin_survey.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :question
    = f.text_field :question
  .field
    = f.label :answer_1
    = f.text_field :answer_1
  .field
    = f.label :answer_2
    = f.text_field :answer_2
  .field
    = f.label :answer_3
    = f.text_field :answer_3
  .field
    = f.label :answer_4
    = f.text_field :answer_4
  .field
    = f.label :answer_5
    = f.text_field :answer_5
  .actions
    = f.submit 'Сохранить', class: 'btn btn-success'

app/views/admin/surveys/edit.html.haml
%h1 Редактировать опрос

= render 'form'

= link_to 'Назад', admin_surveys_path

app/views/admin/surveys/index.html.haml
%h1 Опросы
= link_to 'Новый опрос', new_admin_survey_path, class: 'btn btn-success'

%table.table
  %tr
    %th Вопрос
    %th Ответ №1
    %th Ответ №2
    %th Ответ №3
    %th Ответ №4
    %th Ответ №5
    %th
    %th
    %th

  - @admin_surveys.each do |admin_survey|
    %tr
      %td= admin_survey.question
      %td= admin_survey.answer_1
      %td= admin_survey.answer_2
      %td= admin_survey.answer_3
      %td= admin_survey.answer_4
      %td= admin_survey.answer_5
      %td= link_to 'Показать', admin_survey, class: 'btn btn-success'
      %td= link_to 'Редактировать', edit_admin_survey_path(admin_survey), class: 'btn btn-warning'
      %td= link_to 'Удалить', admin_survey, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

%br

app/views/admin/surveys/new.html.haml
%h1 Новый опрос

= render 'form'

= link_to 'Назад', admin_surveys_path

app/views/admin/surveys/show.html.haml
%p#notice= notice

%h2 Результаты:
- 5.times do |i|
  - ans = @admin_survey.send("answer_#{i+1}")
  - unless ans.blank?
    .row
      .col-lg-2
        = ans + ':'
      .col-lg-10
        - denominator = @admin_survey.survey_results.where("result = #{i}").count
        - unless denominator == 0
          =  number_to_percentage 100 * denominator / @admin_survey.survey_results.count, precision: 2
        - else
          = "0%"
        = " (#{denominator} из #{@admin_survey.survey_results.count})"


%p
  %b Question:
  = @admin_survey.question
%p
  %b Answer 1:
  = @admin_survey.answer_1
%p
  %b Answer 2:
  = @admin_survey.answer_2
%p
  %b Answer 3:
  = @admin_survey.answer_3
%p
  %b Answer 4:
  = @admin_survey.answer_4
%p
  %b Answer 5:
  = @admin_survey.answer_5

= link_to 'Edit', edit_admin_survey_path(@admin_survey)
\|
= link_to 'Back', admin_surveys_path