config/routes.rb
Moika::Application.routes.draw do


  get 'mobile/admin'
  get 'mobile/requests'
  get 'mobile/subscribes'
  # Sorry
  get 'about', to: 'static_pages#show', permalink: 'new_about' 

  resources :images, only:[:update, :destroy]


  resources :survey_results, only: [:index,:create]
  namespace :admin do
    resources :surveys
  end

  get 'proposals', to: 'proposals#index'
  resources :reviews, only: [:index]

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forum'


  resources 'news', only: [:index, :show], controller: 'posts', type: 'NewsPost', as: 'news_posts'
  resources 'info', only: [:index, :show], controller: 'posts', type: 'InfoPost', as: 'info_posts'
  get 'video', to: 'video_posts#index'
  # get 'temp_session/login'
  resources :temp_session
  # resources :navs

  get 'posts(/:id)', to: redirect('/news/%{id}')
  # resources :posts, only: [:index,:show]
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get "normal_users/show"
  root 'map#show'
  # get "map/show"

  get "sp/:id", to: "static_pages#show", as: "static_page"
  get "banners/update"

  get "user/:id", to: "users#show", as: '/user'
  get "users/registration", to: "users#registration", as: 'registration'
  get "users/login", to: "users#login", as: 'login'

  get "normal_user/:id", to: "normal_users#show", as: '/normal_user'

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :normal_users, controllers: { registrations: "registrations", sessions: "sessions" }

  get "update_password", to: "users#update_password", as: "/update_password"
  post "update_password", to: "users#update_password"
  # resource :user do
  #   collection do
  #     post 'update_password'
  #   end
  # end

  resources :car_washes do
    get :update_map, on: :collection
    patch :update_widget_of, on: :member
    resource :widget
    resources :comments, only: [:index, :create]
    resources :requests do 
      # some spammers got me always going to this page
      collection do
        get 'legal', to: 'requests#legal'
      end
    end
    resources :messages, only: [:index, :show, :update]
    resources :normal_user_messages
    resources :banners, only: [:index, :update]
    resources :payments, only: [:index]
    resources :invoices, only: [:new, :create, :show]
    delete 'delete_file/:id', to: 'banners#delete_file', as: '/delete_file'
    resources :reviews
    resources :videos, except: [:index]
    resources :images, except: [:index]
  end
  get 'car_washes/:id/edit(/:cw_tabs_selected_tab)', :to => 'car_washes#edit', as: 'edit_car_wash_with_tab'
  # get 'car_washes/:id(/:cw_tabs_selected_tab)', :to => 'car_washes#show', as: 'show_car_wash_with_tab'
  put 'car_washes/:id/update_main_action', to: 'car_washes#update_main_action', as: '/car_washes_update_main_action'
  post 'car_washes/:id/subscribe/:user_id', to: 'car_washes#subscribe', as: '/car_washes_subscribe'


  scope '/robokassa' do
    %w(paid success fail).map do |route|
      method(Rubykassa.http_method).call "/#{route}" => "robokassa##{route}", as: "robokassa_#{route}" 
    end
  end
  # controller :robokassa do
  #   get "robokassa/:notification_key/notify"   => :notify,  :as => :robokassa_notification
  #   get "robokassa/paid"   => :paid,  :as => :robokassa_payment

  #   get "robokassa/success"  => :success, :as => :robokassa_on_success
  #   get "robokassa/fail"     => :fail,    :as => :robokassa_on_fail
  # end

  namespace :admin do
    get '', to: 'dashboard#main', as: '/'
    # get 'ads', to: 'settings#ads_index', as: 'ad_settings'
    # put 'ads', to: 'settings#ads_update'
    patch 'cube_ads', to: 'advertisements#update', :type => 'CubeAd'
    patch 'marquee_ads', to: 'advertisements#update', :type => 'MarqueeAd'
    resources :cube_ads, :controller => 'advertisements', :type => 'CubeAd'
    resources :marquee_ads, :controller => 'advertisements', :type => 'MarqueeAd'
    resources :ad_settings
    resources :mq_settings
    resources :settings
    get 'load_data_from_ya', to: 'dashboard#load_data_from_ya', as: '/load_data_from_ya'
    post 'users/create_admin'
    get 'users/new_admin'
    post 'users/destroy_admin'
    resources :users
    resources :messages, only: [:index, :show, :create, :destroy]
    resources :banners
    resources :banners_config, only: [:update]
    resources :static_pages
    resources :car_washes
    resources :posts
    resources :news_posts, :controller => 'posts', :type => 'NewsPost'
    resources :info_posts, :controller => 'posts', :type => 'InfoPost'
    resources :video_posts
    resources :post_categories
    resources :navs do
      post :update_position, on: :collection
    end 
    # devise_for :users, only: [:update, :index, :show]
    get 'add_car_wash/:id', to: 'users#add_car_wash', as: '/add_car_wash'
    delete 'delete_file/:id', to: 'banners#delete_file', as: '/delete_file'
  end

  get ':permalink', to: 'static_pages#show'
  match "*path" => redirect("/"), via: :all


end

app/models/video_post.rb
class VideoPost < Post

  def type_name
    'Видео-публикация'
  end

  # def self.model_name
  #   Post.model_name
  # end


end

app/controllers/admin/video_posts_controller.rb
class Admin::VideoPostsController < AdminController
  before_action :set_admin_video_post, only: [:show, :edit, :update, :destroy]

  # GET /admin/posts
  # GET /admin/posts.json
  def index
    @admin_video_posts = VideoPost.all
    @admin_video_post_categories = PostCategory.all
  end

  # GET /admin/posts/1
  # GET /admin/posts/1.json
  def show
  end

  # GET /admin/posts/new
  def new
    @admin_video_post = VideoPost.new
  end

  # GET /admin/posts/1/edit
  def edit
    @admin_video_post = VideoPost.find params[:id]
  end

  # POST /admin/posts
  # POST /admin/posts.json
  def create
    # params[:post][:type] = params[:type]

    @admin_video_post = VideoPost.new(admin_video_post_params)

    respond_to do |format|
      if @admin_video_post.save
        format.html { redirect_to admin_video_post_path(@admin_video_post), notice: 'Публикация успешно создана' }
        format.json { render action: 'show', status: :created, location: @admin_video_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_video_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/posts/1
  # PATCH/PUT /admin/posts/1.json
  def update
    respond_to do |format|
      if @admin_video_post.update(admin_video_post_params)
        format.html { redirect_to admin_video_post_path(@admin_video_post), notice: 'Публикация успешно обновлена' }
        format.json { render action: 'show', status: :ok, location: @admin_video_post }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_video_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/posts/1
  # DELETE /admin/posts/1.json
  def destroy
    @admin_video_post.destroy
    respond_to do |format|
      format.html { redirect_to admin_video_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_video_post
      @admin_video_post = VideoPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_video_post_params
      params.require(:video_post).permit(:title, :subtitle, :content, :bootsy_image_gallery_id, :type, :post_category_id)
    end
end

app/controllers/video_posts_controller.rb
class VideoPostsController < ApplicationController

  def index
    @posts = VideoPost.all
  end

  def show
    @post = VideoPost.all
  end

end

app/views/admin/video_posts/_form.html.haml
= form_for [:admin,@admin_video_post],role: 'form' do |f|
  - if @admin_video_post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_video_post.errors.count, "error")} prohibited this admin_post from being saved:"
      %ul
        - @admin_video_post.errors.full_messages.each do |msg|
          %li= msg
  =f.hidden_field :type
  .form-group
    = f.label "Заголовок"
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label "Описание"
    = f.text_field :subtitle, class: 'form-control'
  .form-group
    = f.label "Категория"
    = f.collection_select(:post_category_id, PostCategory.all, :id, :name, prompt: "Выберите категорию:")

  .form-group
    = f.label "Ссылка"
    = f.text_field :content, class: 'form-control col-lg-10'

  %br
  %hr
  .row
    .col-lg-4.col-lg-offset-4
      = f.submit t("save_button"), class: 'btn btn-danger btn-block'

app/views/admin/video_posts/edit.html.haml
%h1 Видео-публикация

= render 'form'

= link_to t('show_link'), admin_video_post_path(@admin_video_post), class: "btn btn-warning"
\|
= link_to t('back_link'), admin_video_posts_path, class: "btn btn-success"

app/views/admin/video_posts/index.html.haml
%ul.nav.nav-tabs#users
  %li.active
    =link_to "Публикации", "#videos", data:{toggle: "tab"}
  %li
    =link_to "Категории", "#categories", data:{toggle: "tab"}
.tab-content
  .tab-pane.fade.active.in#videos
    %br
    .row
      .col-lg-12
        = link_to 'Создать видео-публикацию', new_admin_video_post_path, class: 'btn btn-success'
    %h1= t('Видео')

    %table.table
      %tr
        %th Заголовок
        %th Подзаголовок
        %th Категория
        %th Тип
        %th Дата создания
        %th
        %th

      - @admin_video_posts.each do |admin_post|
        %tr
          %td= admin_post.title
          %td= admin_post.subtitle
          %td= admin_post.post_category.try(:name)
          %td= admin_post.type_name
          %td= admin_post.created_at.localtime.strftime("%H:%M %d.%m.%Y")
          %td= link_to t('show_link'), admin_video_post_path(admin_post), class: 'btn btn-success'
          %td= link_to t('edit_button'), edit_admin_video_post_path(admin_post), class: 'btn btn-warning'
          %td= link_to t('delete_button'), admin_video_post_path(admin_post), :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: 'btn btn-danger'
  .tab-pane.fade#categories
    %br
    .row
      %h1= t('Категории')
      .col-lg-12
        = link_to 'Создать', new_admin_post_category_path, class: 'btn btn-success'

    %table.table.cats
      %tr
        %th Название
        %th
        %th

      - @admin_video_post_categories.each do |cat|
        %tr
          %td= cat.name
          %td= link_to t('edit_button'), edit_admin_post_category_path(cat), class: 'btn btn-warning'
          %td= link_to t('delete_button'), admin_post_category_path(cat), :method => :delete, :data => { :confirm => 'Вы уверены?' }, class: 'btn btn-danger'

app/views/admin/video_posts/new.html.haml
%h1 Видео публикация

= render 'form'

= link_to t('back_link'), admin_posts_path(), class: "btn btn-success"

app/views/admin/video_posts/show.html.haml
%p#notice= notice

%ul.list-group
  %li.list-group-item= @admin_video_post.title
  %li.list-group-item= @admin_video_post.subtitle
  %li.list-group-item= @admin_video_post.post_category.try(:name)
  %li.list-group-item=sanitize @admin_video_post.content

= link_to t('edit'), edit_admin_video_post_path(@admin_video_post), class: "btn btn-warning"
\|
= link_to t('back_link'), admin_video_posts_path, class: "btn btn-success"